### ISSUE TITLE
Is the .engine file can be used in C++

### ISSUE THREAD

**Issue by github2016-yuan** [BlueMirrors/Yolov5-TensorRT#4]
Thank you for your repo and I have converted yolov5s.onnx to yolov5s.engine。
Now I use it in C++ but get the error : Deserial the cuda engine failed.

I wonder if the trt file get by the repo can be used in C++

**Comment by shivamswarnkar** [comment]
Hi @github2016-yuan We will get back to you on this.

**Comment by makaveli10** [comment]
@github2016-yuan Yes, you can sucessfully deserialize python tensorrt model using c++. We have tested and did not get the "Deserial the cuda engine failed". We think that you faced this error because of mismatch between python and C++ tensorrt version. 

P.S. soon we will release the a new version with c++ deserialization support.
Thanks

**Comment by rashmi-learning** [comment]
@shivamswarnkar, Thanks for writing the tensorRT conversion and inference script. However, when I convert the model to fp16 it reduces the accuracy. Is there any configuration so that I convert the model to tensorRT but does not need to change the precesion to fp16 and convert the model with fp32. Thank you
